#pragma once


#define CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CONST, A, B)		\
	CM_FUNC_QUALIFIER vec<2, T, Q> A##B() CONST	\
	{											\
		return vec<2, T, Q>(this->A, this->B);	\
	}

#define CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CONST, A, B, C)		\
	CM_FUNC_QUALIFIER vec<3, T, Q> A##B##C() CONST			\
	{														\
		return vec<3, T, Q>(this->A, this->B, this->C)		\
	}

#define CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CONST, A, B, C, D)		\
	CM_FUNC_QUALIFIER vec<4, T, Q> A##B##C##D() CONST			\
	{														\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D)		\
	}

#define CM_SWIZZLE_GEN_VEC2_ENTRY_DEF(T, P, L, CONST, A, B)		\
	CM_FUNC_QUALIFIER vec<2, T, Q> vec<L, T, Q>::A##B() CONST	\
	{											\
		return vec<2, T, Q>(this->A, this->B);	\
	}

#define CM_SWIZZLE_GEN_VEC3_ENTRY_DEF(T, P, L, CONST, A, B, C)		\
	CM_FUNC_QUALIFIER vec<3, T, Q> vec<L, T, Q>::A##B##C() CONST			\
	{														\
		return vec<3, T, Q>(this->A, this->B, this->C)		\
	}

#define CM_SWIZZLE_GEN_VEC4_ENTRY_DEF(T, P, L, CONST, A, B, C, D)		\
	CM_FUNC_QUALIFIER vec<4, T, Q> vec<L, T, Q>::A##B##C##D() CONST			\
	{														\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D)		\
	}



#define CM_MUTABLE	

#define CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, A, B)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, B)\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, A)

#define CM_SWIZZLE_GEN_REF_FROM_VEC2(T, P)\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, x, y)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, r, g)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, s, t)

#define CM_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE(T, P, A, B, C)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, B)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, C)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, A)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, C)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, C, A)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, C, B)

#define CM_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE(T, P, A, B, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, B, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, C, B)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, A, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, C, A)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, A, B)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, B, A)

#define CM_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, A, B, C)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE(T, P, A, B, C)	\
		CM_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE(T, P, A, B, C)

#define CM_SWIZZLE_GEN_REF_FROM_VEC3(T, P)\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, x, y, z)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, r, g, b)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, s, t, p)


#define CM_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, B)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, C)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, A, D)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, A)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, C)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, B, D)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, C, A)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, C, B)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, C, D)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, D, A)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, D, B)	\
		CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_MUTABLE, D, C)
		

#define CM_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, B, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, B, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, C, B)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, C, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, D, B)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, A, D, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, A, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, C, A)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, A, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, D, A)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, C, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, B, D, C)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, A, B)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, B, A)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, A, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, D, A)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, B, D)	\
		CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_MUTABLE, C, D, B)

#define CM_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, B, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, D, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, B, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, C, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, D, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, C, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, A, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, D, A) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, A, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, C, A) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, D, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, C, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, A, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, D, A) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, A, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, B, A) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, D, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, B, D) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, B, A) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, A, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, B, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, C, B) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, A, C) \
		CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, C, A)

#define CM_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)	\
		CM_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)

#define CM_SWIZZLE_GEN_REF_FROM_VEC4(T, P)\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, x, y, z, w)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, r, g, b, a)	\
		CM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, s, t, p, q)

#define CM_CONST const

#define CM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, B)

#define CM_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, B)

#define CM_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, B)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE(T, P, A, B) \
	CM_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE(T, P, A, B)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC2(T, P)			\
	CM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, x, y)	\
	CM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, r, g)	\
	CM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, s, t)

#define CM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, C)

#define CM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, C)

#define CM_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, C)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE(T, P, A, B, C)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC3(T, P) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, x, y, z) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, r, g, b) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, s, t, p)

#define CM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, A, D) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, B, D) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, C, D) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, D, A) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, D, B) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, D, C) \
	CM_SWIZZLE_GEN_VEC2_ENTRY(T, P, CM_CONST, D, D)

#define CM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, A, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, B, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, C, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, D, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, D, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, D, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, A, D, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, A, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, B, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, C, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, D, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, D, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, D, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, B, D, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, A, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, B, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, C, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, D, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, D, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, D, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, C, D, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, A, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, A, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, A, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, A, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, B, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, B, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, B, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, B, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, C, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, C, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, C, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, C, D) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, D, A) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, D, B) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, D, C) \
	CM_SWIZZLE_GEN_VEC3_ENTRY(T, P, CM_CONST, D, D, D)

#define CM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, A, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, B, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, C, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, A, D, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, A, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, B, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, C, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, B, D, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, A, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, B, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, C, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, C, D, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, A, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, B, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, C, D, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, A, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, A, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, A, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, A, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, B, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, B, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, B, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, B, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, C, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, C, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, C, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, C, D) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, D, A) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, D, B) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, D, C) \
	CM_SWIZZLE_GEN_VEC4_ENTRY(T, P, CM_CONST, D, D, D, D)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	CM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)

#define CM_SWIZZLE_GEN_VEC_FROM_VEC4(T, P) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, x, y, z, w) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, r, g, b, a) \
	CM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, s, t, p, q)
